### ISSUE TITLE
flow brakes from *nix standard

### ISSUE THREAD

**Issue by GrayHatter** [Famicoman/ia-collection-dl#1]
Default should clone to a subdirectory in the current directory. Similar to git; that way it can be called from a script with a list of projects to copy. That way one can quickly create a new web mirror without much interaction.

**Comment by Famicoman** [comment]
It looks like the way the internet archive module works is that it just pulls the current path to save to. I cant send it a path. Theoretically I can have it download each item into the current director then immediately move it into the overall collection directory as you describe.

**Comment by GrayHatter** [comment]
​change directory inside the script, call ai function, cd back out?​
